<?php
$title = $this->translate('Bearbeiten');
$this->headTitle($title);
?>
<div class="gitter">

	<!-- Platzhalter fuer das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<a href="<?php echo $this->url('sportevent')?>">
			<div class="window2">
				◁ <?php echo $this->translate("Zur&uuml;ck") ?>
			</div>
		</a>
	</div>
	
	<!-- Platzhalter fuer das Layout -->
	<div class="col-1-4"></div>
	
	<!-- Platzhalter fuer das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<div class="window2n">
			<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>
			<small><?php $this->translate("Beschreibe hier, wie gut du in dieser Sportart bist oder warum du sie magst"); ?></small>
		</div>
	</div>
	
	<!-- Platzhalter fuer das Layout -->
	<div class="col-1-4"></div>
	
	<!-- Platzhalter fuer das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<div class="window2n" style="text-align: right; display:block;">
			<?php
				$form = $this->form;
				$form->setAttribute('action', $this->url('lieblingssportart', array('action' => 'edit', 'id' => $this->id,)));
				$form->prepare();
				
				echo $this->form()->openTag($form);
				echo $this->formHidden($form->get('sportart_id'));
				echo $this->formHidden($form->get('mitglied_id'));
				echo $this->formRow($form->get('beschreibung'));
				echo $this->formRow($form->get('level'));
				echo $this->formSubmit($form->get('submit'));
				echo $this->form()->closeTag();
			?>
		</div>
	</div>
	
</div>