<?php
$title = $this->translate('Sportart l&ouml;schen');
$this->headTitle($title);
?>
<div class="gitter">

	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<a href="<?php echo $this->url('sportarten')?>">
			<div class="window2">
				◁ <?php echo $this->translate("Zur&uuml;ck") ?>
			</div>
		</a>
	</div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<div class="window2n">
			<h1><?php echo $title; ?></h1>
		</div>
	</div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<div class="window2n" style="text-align: right; display:block;">
			<p><?php echo ($this->translate("Bist du sicher, dass du die Sportart l&ouml;schen m&ouml;chtest")); ?>?<br/>
			'<?php echo $this->escapeHtml($sportart->titel); ?>'
			</p>
			<?php
			$url = $this->url('sportarten', array(
			    'action' => 'delete',
			    'id'     => $this->id,
			));
			?>
			<!-- Die Meldung wird angezeigt mit "Yes" und "No" Buttons-->
			<form action="<?php echo $url; ?>" method="post">
			<div>
			    <input type="hidden" name="id" value="<?php echo (int) $sportart->sportart_id; ?>" />
			    <input type="submit" name="del" value="<?php echo $this->translate('Ja'); ?>" />
			    <input type="submit" name="del" value="<?php echo $this->translate('Nein'); ?>" />
			</div>
			</form>
		</div>
	</div>
	
</div>