<?php
$titel =$this->escapeHtml($this->translate("Willkommen!"));
$this->headTitle($titel);
?>
<div class="gitter">
	
	<?php 
	// Nur angemeldete User duerfen ein Sportevent erstellen
	if(isset($mitglied_id))
	{
	?>
		<div class="col-3-4">
			<!-- Link, um eine neue Sportart hinzuzufuegen-->
			<a href="<?php echo $this->url('sportarten', array('action'=>'add'))?>">
				<div class="window2">
				+ <?php echo($this->translate("Neue Sportart"))?>
				</div>
			</a>
		</div>
    <?php 
	}
    ?>

	<!-- Anmelde/ZumProfil-Link -->
	<?php 
	if(isset($mitglied_id))
	{
	?>
		<div class="col-1-4">
			<a href="<?php echo $this->url('profil', array('action'=>'index'))?>">
				<div class="window2">
				    <b><?php echo $this->escapeHtml($mitglied_name);?></b>
				</div>
			</a>
		</div>
	<?php 
	}
	else 
	{
	?>
		<div class="col-1-1">
			<a href="<?php echo $this->url('login', array('action'=>'index'))?>">
				<div class="window2">
				    <b><?php echo($this->translate("Anmelden oder Registrieren")) ?></b>
				</div>
			</a>
		</div>
	<?php 
	}
	?>

	
	<!-- Titel der Startseite -->
	<div class="col-1-1">
		<div class="window2n">
			<h1><?php echo $this->escapeHtml($titel); ?></h1>
			<b><?php echo($this->translate("Bitte w&auml;hle eine Sportart aus, die dir gef&auml;llt")) ?></b>
		</div>
	</div>

	<?php foreach ($sportarten as $sportart) : ?>
		<div class="col-1-3">
			<a href="<?php echo $this->url('sportart', array('action'=>'index', 'id' => $sportart->sportart_id))?>">
				<div class="window3">
					<img style="background-position: center; height: 130px; width: 100%; background: transparent url('meinbild.jpg') center no-repeat;"
 						 src="<?php echo (empty($sportart->bild_url)) ? "/images/sportevent.JPG" : '/upload/sportart/' . $sportart->bild_url; ?>">
			    	<h2><?php echo $this->escapeHtml($sportart->titel);?></h2>
								    
					<?php 
			    	// Nur Admin (0) darf bearbeiten und l&ouml;schen
			    	if(isset($mitglied_id) && $mitglied_id == 0)
			    	{
			    	?>
					   	<div class="window3" style="up: 0px; position: absolute; left: 0px; ">
				   			<a href="<?php echo $this->url('sportarten', array('action'=>'edit', 'id' => $sportart->sportart_id))?>">✎</a>	<!-- Link zur Bearbeitung des Datensatzes-->
				   		</div>
				   		<div class="window3" style="up: 0px; position: absolute; left: 40px; ">
			        		<a href="<?php echo $this->url('sportarten', array('action'=>'delete', 'id' => $sportart->sportart_id))?>">&#10008;</a>    <!-- Link zum L&ouml;schen des Datensatzes-->

				        </div>
			      	<?php 
			    	}
			        ?>
			    </div>		        
			</a>	
		</div>			
	<?php endforeach; ?>

</div>