<?php
$title = $this->translate("Neues")." ".$this->escapeHtml($this->escapeHtml($sportart->titel))."-".$this->translate("Event");
$this->headTitle($title);
?>
<div class="gitter">

	<div class="col-1-4">
		<a href="<?php echo $this->url('sportart'); ?>">
			<div class="window2">
				◁ <?php echo $this->translate("Zur&uuml;ck"); ?>
			</div>
		</a>
	</div>
	
	<div class="col-1-1">
		<div class="window2n">
			<h1><?php echo $title; ?></h1>
		</div>
	</div>
	
	<div class="col-3-4">
		<div class="window2n" style="text-align: right; display:block;">
			<?php
				$form = $this->form;
				$form->setAttribute('action', $this->url('sportart', array('action' => 'add')));
				$form->prepare();
				
				echo $this->form()->openTag($form);
				echo $this->formCollection($form);
				echo $this->form()->closeTag();
			?>
		</div>
	</div>
	
	<div class="col-1-4">
		<div class="gitter">
			<div class="col-1-1">
				<div class="window2n">
					<img src="<?php echo $this->basePath()."/images/sportevent.JPG"; ?>">
				</div>
			</div>		
		</div>
	</div>
	
</div>