<?php
$title = $this->translate('Sportevent bearbeiten');
$this->headTitle($title);
?>
<div class="gitter">

	<div class="col-1-4">
		<a href="<?php echo $this->url('sportart'); ?>">
			<div class="window2">
				◁  <?php echo $this->translate("Zur&uuml;ck"); ?>
			</div>
		</a>
	</div>
	
	<div class="col-1-1">
		<div class="window2n">
			<h1><?php echo $title; ?></h1>
		</div>
	</div>
	
	<div class="col-3-4">
		<div class="window2n" style="text-align: right; display:block;">
			<?php
				$form = $this->form;
				
				$form->setAttribute('action', $this->url(
				    'sportart',
				    array(
				        'action' => 'edit',
				        'id'     => $this->id,
				    )
				));
				$form->prepare();
			?>
			
			<?php  echo $this->form()->openTag($form);?>
			<?php  echo $this->formHidden($form->get('sportevent_id'));?>
			<?php  echo $this->formHidden($form->get('sportart_id'));?>
			<?php  echo $this->formHidden($form->get('mitglied_id'));?>
			<?php echo $this->formRow($form->get('titel')); ?>
			<?php echo $this->formRow($form->get('beschreibung'));?>
			<?php echo $this->formRow($form->get('adresse'));?>
			<?php echo $this->formRow($form->get('ort'));?>
			<?php echo $this->formRow($form->get('startdatum'));?>
			<?php echo $this->formRow($form->get('enddatum'));?>
			<?php echo $this->formRow($form->get('startuhrzeit'));?>
			<?php echo $this->formRow($form->get('enduhrzeit'));?>
			<?php echo $this->formRow($form->get('level'));?>
			<?php echo $this->formSubmit($form->get('submit'));?>
			<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>

	<div class="col-1-4">
		<div class="gitter">
			<div class="col-1-1">
				<div class="window2n">
					<img src="<?php echo $this->basePath()."/images/sportevent.JPG"; ?>">
				</div>
			</div>
		</div>
	</div>
	
</div>