<?php
$titel = $this->escapeHtml($sportart->titel);
$this->headTitle($titel);
?>
<div class="gitter">
	
	<!-- Navigation Zur&uuml;ck zu Auswahlseiten -->
	<div class="col-1-4">
		<a href="<?php echo $this->url('sportarten'); ?>">
			<div class="window2">
				◁ <?php echo$this->translate("Sportarten"); ?>
			</div>
		</a>
	</div>
	
	<?php 
	// Nur angemeldete User d&uuml;rfen ein Sportevent erstellen
	if(isset($mitglied_id))
	{
	?>
		<div class="col-1-2">
			<a href="<?php echo $this->url('sportart', array('action'=>'add')); ?>">
				<div class="window2">
					+ <?php echo($this->translate("Neues Sportevent")); ?>
				</div>
			</a>
		</div>
    <?php 
	}
    ?>

	<!-- Anmelde/ZumProfil-Link -->
	<?php 
	if(isset($mitglied_id))
	{
	?>
		<div class="col-1-4">
			<a href="<?php echo $this->url('profil', array('action'=>'index')); ?>">
				<div class="window2">
				    <b><?php echo $this->escapeHtml($mitglied_name); ?></b>
				</div>
			</a>
		</div>
	<?php 
	}
	else 
	{
	?>
		<div class="col-3-4">
			<a href="<?php echo $this->url('login', array('action'=>'index')); ?>">
				<div class="window2">
				    <b><?php echo($this->translate("Anmelden oder Registrieren")); ?></b>
				</div>
			</a>
		</div>
	<?php 
	}
	?>
	
	<!-- Titel der Sportart und Sportart-Geaellt-Mir-Button -->
	<div class="col-1-1">
		<div class="window2n">
			<h1><?php echo $this->escapeHtml($titel); ?></h1>
			
			<?php 
			if(!isset($ist_lieblingssportart))
			{
			?>
				<a href="<?php echo $this->url('lieblingssportart', array('action'=>'add')); ?>">
					&#10084; <?php echo $this->translate("Diese Sportart als meine Lieblingssportart markieren"); ?>
				</a>
			<?php 
			}
			else 
			{
			?>
				<a href="<?php echo $this->url('lieblingssportart', array('action'=>'delete', 'id'=>$sportart->sportart_id)); ?>">
					&#10008; <?php echo $this->translate("Als Lieblingssportart entfernen"); ?>
				</a>
			<?php 
			}
			?>
		</div>
	</div>
	
	<?php $zaehler = 0; ?>
	<?php foreach ($sportevents as $sportevent) : ?>
		<div class="col-1-1">
			<a href="<?php echo $this->url('sportevent', array('action'=>'index', 'id' => $sportevent->sportevent_id)); ?>">
				<div class="window3" <?php if($zaehler++ % 2 == 0) echo " style='background-color: #FED'"; ?>>
					
					<div class="gitter">
						<div class="col-1-2" style="color: black;">
					    	<b><?php echo $this->escapeHtml($sportevent->titel);?></b>
					    	<br/>
						    <small style="color: #766;"><?php echo $this->escapeHtml($sportevent->beschreibung);?></small>
						</div>
						<div class="col-1-4" style="color: black;">
					    	<?php echo $this->escapeHtml($sportevent->adresse);?><br/>
						    <?php echo $this->escapeHtml($sportevent->ort);?>
						</div>
						<?php 
						if($sportevent->startdatum <= date('Y-m-d'))
						{
							$startdatum = new DateTime($sportevent->startdatum);
							?>
							<div class="col-1-4"style="color: black;">
								<?php
									echo "(war am ".$startdatum->format('d.m.Y').")";
								?>
							</div>
							<?php
						}
						else 
						{
						?>
							<div class="col-1-8"style="color: black;">
								<?php 
									$startdatum = new DateTime($this->escapeHtml($sportevent->startdatum));
									$enddatum = new DateTime($this->escapeHtml($sportevent->enddatum));
								?>
						    	<small style="color: #766;"><?php echo($this->translate("Von")); ?> :</small> <?php echo $startdatum->format('d.m.Y'); ?><br/>
							    <small style="color: #766;"><?php echo($this->translate("Bis")); ?> :</small> <?php echo $enddatum->format('d.m.Y'); ?>
							</div>
							<div class="col-1-8"style="color: black;">
								<?php 
									$startuhrzeit = new DateTime($this->escapeHtml($sportevent->startuhrzeit));
									$enduhrzeit = new DateTime($this->escapeHtml($sportevent->enduhrzeit));
								?>
						    	<small style="color: #766;"><?php echo($this->translate("Von")); ?> :</small> <?php echo $startuhrzeit->format('H:m'); ?><br/>
							    <small style="color: #766;"><?php echo($this->translate("Bis")); ?> :</small> <?php echo $enduhrzeit->format('H:m'); ?>
							</div>
						<?php 
						}
						?>
					</div>

					<?php
			    	// Nur Admin (0) oder Verfasser des Sportevents d&uuml;rfen bearbeiten und l&ouml;schen
					if(isset($mitglied_id))
					{
				    	if($mitglied_id == 0 || $mitglied_id == $sportevent->mitglied_id)
				    	{
				    	?>
						   	<div class="window2" style="up: 0px; position: absolute; left: 0px; ">
					   			<a href="<?php echo $this->url('sportart', array('action'=>'edit', 'id' => $sportevent->sportevent_id)); ?>">✎</a>
					   		</div>
					   		<div class="window2" style="up: 0px; position: absolute; left: 40px; ">
				        		<a href="<?php echo $this->url('sportart', array('action'=>'delete', 'id' => $sportevent->sportevent_id)); ?>">&#10008;</a>
					        </div>
				      	<?php 
				    	}
					}
			        ?>
			    </div>		        
			</a>	
		</div>			
	<?php endforeach; ?>

</div>