<?php
$title = $this->translate('Profil l&ouml;schen');
$this->headTitle($title);
?>
<div class="gitter">

	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<a href="<?php echo $this->url('profil')?>">
			<div class="window2">
				◁ <?php echo $this->translate("Zur&uuml;ck") ?>
			</div>
		</a>
	</div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<div class="window2n">
			<h1><?php echo $title; ?></h1>
		</div>
	</div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<div class="window2n" style="text-align: right; display:block;">
			'<?php echo $this->translate("Achtung")." ".$this->escapeHtml($mitglied_name); ?>'
			<p> <?php echo  $this->translate("Magst du dein Profil wirklich l&ouml;schen"); ?>?
			
			</p>
			<?php
			$url = $this->url('profil', array(
			    'action' => 'delete',
			));
			?>
			<form action="<?php echo $url; ?>" method="post">
			<div>
			    <input type="submit" name="del" value="<?php echo $this->translate("Ja"); ?>" />
			    <input type="submit" name="del" value="<?php echo $this->translate("Nein"); ?>" />
			</div>
			</form>
		</div>
	</div>
	
</div>