<?php
$title = $this->translate('Profil bearbeiten');
$this->headTitle($title);
?>
<div class="gitter">

	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<a href="<?php echo $this->url('profil')?>">
			<div class="window2">
				◁ <?php echo $this->translate("Zur&uuml;ck") ?>
			</div>
		</a>
	</div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<div class="window2n">
			<h1><?php echo $this->escapeHtml($this->translate($title)); ?></h1>
		</div>
	</div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<!-- Platzhalter f&uuml;r das Layout -->
	<div class="col-1-4"></div>
	
	<div class="col-1-2">
		<div class="window2n" style="text-align: right; display:block;">
			<?php 
				$form = $this->form;
				$form->setAttribute('action', $this->url(
						'profil',
						array(
								'action' => 'edit',
								'id'     => $this->id,
						)
						));
				$form->prepare();
				
				echo $this->form()->openTag($form);
				echo $this->formHidden($form->get('mitglied_id'));
				echo $this->formHidden($form->get('facebook_id'));
				echo $this->formRow($form->get('pseudonym'));
				echo $this->formRow($form->get('passwort'));
				echo $this->formRow($form->get('passwortbestaetigen'));
				echo $this->formRow($form->get('geburtstag'));
				echo $this->formRow($form->get('meine_stadt'));
				echo $this->formRow($form->get('beschreibung'));
				echo $this->formSubmit($form->get('submit'));
				echo $this->form()->closeTag();
			?>
		</div>
	</div>
	
</div>