<?php
$titel = $this->escapeHtml($this->translate("Registrieren"));
$this->headTitle($titel);
?>
<div class="gitter">
	
	<!-- Navigation Zur&uuml;ck zu Auswahlseiten -->
	<div class="col-1-4">
		<a href="<?php echo $this->url('sportarten')?>">
			<div class="window2">
				◁ <?php echo $this->translate("Startseite"); ?>
			</div>
		</a>
	</div>
	
	<!-- Login aufrufen-->
	<div class="col-1-2">
		<a href="<?php echo $this->url('login', array('action'=>'index'))?>">
			<div class="window2">
				<?php echo $this->translate("Zum Login"); ?>
			</div>
		</a>
	</div>
 
	<!-- Anmelde/ZumProfil-Link -->
	<?php 
	if(isset($mitglied_id))
	{
	?>
		<div class="col-1-4">
			<a href="<?php echo $this->url('profil', array('action'=>'index'))?>">
				<div class="window2">
				    <b><?php echo $this->escapeHtml($mitglied_name);?></b>
				</div>
			</a>
		</div>
	<?php 
	}
	else 
	{
	?>
		<div class="col-1-4">
			<div class="window2n">
			    <b> <?php echo $this->translate("Nicht angemeldet"); ?></b>
			</div>
		</div>
	<?php 
	}
	?>
	<div class="col-1-3"></div>
	<!-- Titel der Seite -->
	<div class="col-1-4">
		<br/>
		<br/>
		<h1 style="color: #FFF;"><?php echo $this->escapeHtml($titel); ?></h1>
	</div>
	<div class="col-1-3"></div>
	<?php 
	if(isset($pseudonym_existiert_bereits))
	{
	?>
		<!-- Leeres Feld f&uuml;r Einr&uuml;ckung vom nachfolgendem Div -->
		<div class="col-1-3"></div>
		
		<!-- Das Pseudonym existiert bereits -->
		<div class="col-1-3">
			<div class="window2n" style="background-color: #D54; color: #FFF;">
				<b><?php echo $this->translate("Pseudonym existiert bereits"); ?>!</b><br/>
				<?php echo $this->translate("Bitte w&auml;hle ein anderes Pseudonym aus"); ?>
			</div>
		</div>
		
		<!-- Leeres Feld f&uuml;r Einr&uuml;ckung vom nachfolgendem Div -->
		<div class="col-1-3"></div>
	<?php 
	}
	?>
	
	<?php 
	if(isset($fehler))
	{
	?>
		<!-- Leeres Feld f&uuml;r Einr&uuml;ckung vom nachfolgendem Div -->
		<div class="col-1-3"></div>
		
		<!-- Ein Fehler ist aufgetreten bei der Registrierung -->
		<div class="col-1-3">
			<div class="window2n" style="background-color: #D54; color: #FFF;">
				<b><?php echo $this->translate("Ein Fehler bei der Registrierung ist aufgetreten"); ?></b><br/>
				<?php echo $this->translate("Bitte versuche es erneut"); ?>
			</div>
		</div>
		
		<!-- Leeres Feld f&uuml;r Einr&uuml;ckung vom nachfolgendem Div -->
		<div class="col-1-3"></div>
	<?php 
	}
	?>

	<!-- Leeres Feld f&uuml;r Einr&uuml;ckung vom nachfolgendem Div -->
	<div class="col-1-4"></div>
	
	<!-- Registrieren-Formular -->
	<div class="col-1-2">
		<div class="window2n" style="text-align: right;">
			<?php
			$form = $this->form;
			// Anmeldeformular an die Index-Action senden vom LoginController
			$form->setAttribute('action', $this->url('registrieren', array('action' => 'index')));
			$form->prepare();
			
			echo $this->form()->openTag($form);
			echo $this->formCollection($form);
			echo $this->form()->closeTag();
			?>
		</div>
	</div>
</div>